%% Example MPC controller

clc; close all; clear all;

dt = 0.1;

%% Unicycle Model
sys = CtSystem(...
    'StateEquation', @(t,x,u) [
    u(1)*cos(x(3));
    u(1)*sin(x(3));
    u(2)],...
    'OutputEquation', @(t,x) x(1:2),'ny',2, ... % GPS
    'nx',3,'nu',2 ...
);

desiredPosition = [0;0];

%% <<< BEGIN difference from ex02   

mpcOp = CtMpcOp( ...
    'System'               , sys,...
    'HorizonLength'        , 0.5,...
    'StageConstraints'     , BoxSet( -[1;pi/4],4:5,[1;pi/4],4:5,5),... % on the variable z=[x;u];
    'StageCost'            , @(t,x,u,varargin) (x(1:2)-desiredPosition)'* (x(1:2)-desiredPosition),...
    'TerminalCost'         , @(t,x,varargin) (x(1:2)-desiredPosition)'* (x(1:2)-desiredPosition)...
    );

dtMpcOp = DtMpcOp(mpcOp,dt);

dtSys   = DtSystem(sys,dt);

dtSys.controller = MpcController(...
    'MpcOp'       , dtMpcOp ,...
    'MpcOpSolver' , FminconMpcOpSolver('MpcOp', dtMpcOp,'UseSymbolicEvaluation',1) ...
    );

sys = dtSys;

%% <<< END difference from ex02 

dtSys.stateObserver = EkfFilter(dtSys,...
                 'StateNoiseMatrix'  , diag(([0.1,0.1,pi/4])/3)^2,...
                 'OutputNoiseMatrix' , diag(([0.1,0.1])/3)^2,...
                 'InitialCondition'  , [[1;-1;0];                  %xHat(0)
                                        10*reshape(eye(3),9,1)]);  %P(0)

sys.initialCondition = [1;1;0];

va = VirtualArena(sys,...
    'StoppingCriteria'  , @(t,sysList)norm(sysList{1}.x(1:2)-desiredPosition)<0.1,...
    'DiscretizationStep', dt,...
    'PlottingStep'      , 1, ... 
    'StepPlotFunction'  , @ex02StepPlotFunction ...  %% <<< difference from ex01 ( plot estimate )
    );

log = va.run();

log{1}