%% Easy to use MPC controller

clc;close all;clear all;

dt = 0.1;

%% Unicycle Model
sys = CtSystem(...
    'StateEquation', @(t,x,u) [
    u(1)*cos(x(3));
    u(1)*sin(x(3));
    u(2)],...
    'OutputEquation', @(t,x) x(1:2),'ny',2, ... % GPS
    'nx',3,'nu',2 ...
);

sys.initialCondition = [1;1;0];

desiredPosition = [0;0];

sys.stateObserver = EkfFilter(DtSystem(sys,dt),...
                 'StateNoiseMatrix'  , diag(([0.1,0.1,pi/4])/3)^2,...
                 'OutputNoiseMatrix' , diag(([0.1,0.1])/3)^2,...
                 'InitialCondition'  , [[1;-1;0];                  %xHat(0)
                                        10*reshape(eye(3),9,1)]);  %P(0)

                                    
%% <<< BEGIN difference from ex02                      

mpcOp = CtMpcOp( ...
    'System'               , sys,...
    'HorizonLength'        , 0.5,...
    'StageConstraints'     , BoxSet( -[1;pi/4],4:5,[1;pi/4],4:5,5),... % on the variable z=[x;u];
    'StageCost'            , @(t,x,u) (x(1:2)-desiredPosition)'* (x(1:2)-desiredPosition),...
    'TerminalCost'         , @(t,x) (x(1:2)-desiredPosition)'* (x(1:2)-desiredPosition)...
    );

 mpcOpSolver = AcadoMpcOpSolver(...
     'StepSize',dt,'MpcOp',mpcOp,...
     'AcadoOptimizationAlgorithmOptions', { 'KKT_TOLERANCE',1e-4,'MAX_NUM_ITERATIONS',30 });

sys.controller = MpcController(...
    'MpcOp'                 , mpcOp,...
    'MpcOpSolver'           , mpcOpSolver ...
    );

%% <<< END difference from ex02                     

va = VirtualArena(sys,...
    'StoppingCriteria'  , @(t,sysList)norm(sysList{1}.x(1:2)-desiredPosition)<0.1,...
    'DiscretizationStep', dt,...
    'StepPlotFunction'  , @ex02StepPlotFunction...
    );

log = va.run();

log{1}