%% Custom integrators

clc; clear all; close all;

v1 = UAV(...
    'Controller'        , InlineController(@(x,t)[0.2;0;0;1]),...
    'InitialCondition' , [1;1;0;reshape(eye(3),9,1)] ...
    );

a = VirtualArena(v1,...
    'StoppingCriteria'   , @(i,agentsList)i>20,...
    'StepPlotFunction'   , @stepPlotFunctionPos, ...
    'PlottingStep'       , 1,...
    'DiscretizationStep' , 0.1... %<= add  ",'Integrator',EulerForward()" to see the difference
    ); 

a.run();
