%% Extended Kalman Filter

clc;clear all;close all;
 
v1 = NoisyUnicycle(...
    'Controller',UniGoToPoint([5;5]),...
    'InitialConditions',zeros(3,1),...
    'Q',0.1*eye(3),'R',0.1*eye(3));

% System discretization
dt  = 0.1;
dtV = DtSystem(v1,dt);

% see help GeneralSystem.computeLinearization
dtV.computeLinearization('Sampled');

v1.stateObserver = EkfFilter(dtV,...
            'StateNoiseMatrix'  , eye(3),...
            'OutputNoiseMatrix' , 200*eye(3),...
            'InitialConditions' , [2*ones(3,1);
                                  10*reshape(eye(3),9,1)]);
        
a = VirtualArena(v1,...
    'StoppingCriteria'   , @(i,agentsList)i>300,...
    'StepPlotFunction'   , @stepPlotFunctionEkf, ...
    'PlottingFrequency'  , 10,...
    'DiscretizationStep' , dt);

logs = a.run();
